baseURL               = "https://888niub.com/"
languageCode          = "zh-CN"
title                 = "888牛人导航 - 效率黑科技与AI工具精选"
description           = "888牛人导航 效率黑科技 AI工具 搞钱副业"
theme                 = "WebStack-Hugo"
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true
publishDir            = "docs"

enableRobotsTXT = true

[images]
disableLazyLoading = false

[params]
    author        = "888牛人"
    description   = "888牛人导航 效率黑科技 AI工具 搞钱副业"
    upload        = "https://888niub.com/"
    about         = "https://888niub.com/"
    repository    = "https://github.com/88899"
    enablePreLoad = false
    textPreLoad   = "888牛人导航"
    expandSidebar = true
    logosPath     = "assets/images/logos"
    defaultLogo   = "assets/images/logos/default.webp"
    nightMode     = false
    yiyan         = false

[params.images]
    favicon           = "assets/images/favicon.png"
    searchImageL      = "https://s3.aiedu.qzz.io/website/bg-dna.jpg"
    searchImageD      = "https://s3.aiedu.qzz.io/website/bg-dna-d.jpg"
    logoExpandLight   = "assets/images/wuzi.png"
    logoExpandDark    = "assets/images/wuzi-b.png"
    logoCollapseLight = "assets/images/favicon.png"
    logoCollapseDark  = "assets/images/favicon.png"

[markup.goldmark.renderer]
    unsafe = true

[markup.imageRender]
loading = "lazy"

[params.footer]
    copyright = '2026 By [888牛人导航](https://888niub.com) | 888niub.com <br/>'
